### ISSUE TITLE
javax.el.ValueExpression should be jakarta.el.ValueExpression

### ISSUE THREAD

**Issue by arjantijms** [omnifaces/vdldoc#15]
See:

https://github.com/omnifaces/vdldoc/blob/c45480367f475f7f9dc54d7c5e4775d054420bd0/src/main/resources/org/omnifaces/vdldoc/resources/tag.html.xsl#L488-L492

**Comment by BalusC** [comment]
Indeed!

Fixed now. I'll release a 3.1 soon.

**Comment by arjantijms** [comment]
w00t, thx! :)
