### ISSUE TITLE
Alphabetize the Summary listing

### ISSUE THREAD

**Issue by melloware** [omnifaces/vdldoc#18]
It would be cool if these were alpha order

![image](https://github.com/omnifaces/vdldoc/assets/4399574/4181ed3d-9968-42bc-b982-687cabb8dcdf)

**Comment by BalusC** [comment]
Makes sense.

**Comment by melloware** [comment]
Could we also do the attributes?

![image](https://github.com/omnifaces/vdldoc/assets/4399574/6b179fc0-a70e-4b50-83ee-d269af5123bd)

**Comment by BalusC** [comment]
Of course.

**Comment by melloware** [comment]
you rock!

**Comment by melloware** [comment]
let me know when this is released I will update PrimeFaces VDL.  The sorting will make finding things so much easier!

**Comment by BalusC** [comment]
Done. Will be in central soonish.

**Comment by melloware** [comment]
It is in maven central!  Thanks much!  going to regnerate my docs now.

**Comment by melloware** [comment]
Confirmed it works awesome!   Huge improvement to our docs!
