### ISSUE TITLE
Documentation inside vdldoc elements (vdldoc:deprecation, vdldoc:since, etc) is not processed in taglib.xml files using http://java.sun.com/xml/ns/javaee namespace

### ISSUE THREAD

**Issue by stiemannkj1** [omnifaces/vdldoc#6]
When using the old `javaee` namespace (`http://java.sun.com/xml/ns/javaee`) in `taglib.xml` files, `vdldoc` prefixed elements are not processed, and the generator does not output any of their documentation. **Note:** Documentation using `vdldoc` elements in `taglib.xml` files containing the new `javaee` namespace (`http://xmlns.jcp.org/xml/ns/javaee`) is generated correctly.

Steps to reproduce:

1. Download [example.taglib.xml](https://gist.github.com/stiemannkj1/63a41c05e2b04ee809d5):

        curl https://gist.githubusercontent.com/stiemannkj1/63a41c05e2b04ee809d5/raw/3f5cc4a8414c02e3aafb42ad26382382b955e593/example.taglib.xml -o example.taglib.xml

2. Run vdldoc on `example.taglib.xml`:

        java -jar vdldoc-2.0.jar example.taglib.xml

3. Open `vdldoc/index.html` in your browser.
4. Click the *`example:exampleTag`* link.

If the bug is fixed, `exampleTag` will be <s>strikethrough</s> formatted, the deprecated description will appear ("**Deprecated.** Please use another tag instead."), and "**Since:** 1.0" will appear. If the  bug still exists, none of that formatting or text will appear.

**Comment by BalusC** [comment]
Thank you for the reproducer. I just fixed it. Can you try today's snapshot to confirm?

https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/vdldoc/2.1-SNAPSHOT

**Comment by stiemannkj1** [comment]
@BalusC, It works perfectly! Thanks!
