### ISSUE TITLE
Add option to specify CSS location

### ISSUE THREAD

**Issue by BalusC** [omnifaces/vdldoc#8]
Add option to specify the full value of `<link href>` attribute for the CSS file.

**Comment by edburns** [comment]
Thanks for fixing this so quickly.  Is there a snapshot release that has this fix so I can try it?

**Comment by BalusC** [comment]
It's at sonatype: https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/vdldoc/2.1-SNAPSHOT/

**Comment by edburns** [comment]
Thanks, but I ran into a codehaus reference that seems to be in the overview-summary.html.  I have attached a zip of the generated VDLDoc for the JSF cc: library.

Please see <https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1107> to download the attachment.

**Comment by BalusC** [comment]
It assumed an absolute URI. Now there appears to be ambiguity in the requirement. What exactly did you intend?

- Supply CSS as File and have Vdldoc copy it.
- Supply CSS as URI and have Vdldoc reference it.

**Comment by BalusC** [comment]
I inspected the example in 1107 and identified that you needed to specify a relative CSS URI. Vdldoc has been altered accordingly. You can try today's snapshot.

**Comment by edburns** [comment]
Hooray, thanks, it works: https://maven.java.net/service/local/repositories/snapshots/archive/org/glassfish/javax.faces/2.3.0-m04-SNAPSHOT/javax.faces-2.3.0-m04-20150723.191715-6-documentation.jar/!/vdldoc/index.html
