### ISSUE TITLE
window title always appears as "Overview"

### ISSUE THREAD

**Issue by stiemannkj1** [omnifaces/vdldoc#9]
This may be by design, but the window title for generated VDLdoc always appears as "Overview" even when customized via the `-windowtitle` command line argument. It is likely due to the following line of javascript in [overview-summary.html.xsl](https://github.com/omnifaces/vdldoc/blob/master/src/main/resources/org/omnifaces/vdldoc/resources/overview-summary.html.xsl#L55) (there is similar code in many of the other `.xsl` files):

    if (location.href.indexOf('is-external=true') == -1) parent.document.title = "Overview";

The title appears as "Overview" with or without frames.

**Comment by BalusC** [comment]
They were taken over from javadoc templates. It's more for Oracle's internal usage. I agree that they are unnecessary in Vdldoc.
